version: '3.8'
services:
  nemo1-app:
    build: ../../..
    container_name: nemo1-app
    environment:
      - NODE_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/auth/realms/jhipster
      - BACKEND_ENV=dev
    ports:
      - 8081:8081
  keycloak:
    extends:
      file: keycloak.yml
      service: keycloak
